### ISSUE TITLE
pip install fails with java15

### ISSUE THREAD

**Issue by Reissner** [LeeKamentsky/python-javabridge#180] opened 2020-05-05 13:14 UTC
I try python 3.8.2, java15 and then `pip install javabridge`
The deceicive lines in the error output are 
```
   javac -source 6 -target 6 /tmp/pip-install-8covb3cx/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    error: command 'javac' failed with exit status 2
```
I think, for newer versions it shall be possible to upgrade to java 7 
as version history https://en.wikipedia.org/wiki/Java_version_history 
shows that java 6 ended updates 2013 and lost support 2018. 

Btw: same is true for java-14 and i must go back to java-11 to fix that. 
But in my situation, i cannot do this. Only 14 is a way.

**Comment by LeeKamentsky** [comment] 2020-05-05 15:17
Duplicate of #175 
Until I update PyPi, please try installing like this:
pip3 install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip#egg=python-javabridge

**Closed by LeeKamentsky** 2020-05-05 15:17 UTC
